[package]
name = "android-dl-iterate-phdr-runner"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
darwin-art-elf-loader = { path = "../../crates/darwin-art-elf-loader" }

[features]
provider-link = []

[[bin]]
name = "android-dl-iterate-phdr-runner"
path = "src/main.rs"
required-features = ["provider-link"]
