#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ninja="$root/_aosp/external/skia/third_party/ninja/ninja"
graph_dir="$root/_build/native-graph-audit"
graph="$graph_dir/build.ninja"
mkdir -p "$graph_dir"

if [[ ! -x "$ninja" ]]; then
  echo "native-graph: pinned Ninja is missing: $ninja" >&2
  exit 2
fi

(cd "$root" && cargo run -q -p darwin-art-xtask -- native-graph --out "$graph")

cached_cpp="$(grep -c ': native_cached_cpp ' "$graph" || true)"
cached_archives="$(grep -c ': native_cached_archive ' "$graph" || true)"
icu_cpp="$(grep -c '_build/icu-foundation/objects/.*: native_cached_cpp ' "$graph" || true)"
runtime_cpp="$(grep -c '_build/runtime-bootstrap/objects/.*: native_cached_cpp ' "$graph" || true)"
graphics_cpp="$(grep -c '_build/android-graphics-jni/objects/.*: native_cached_cpp ' "$graph" || true)"

(( icu_cpp >= 458 )) || {
  echo "native-graph: ICU cache incomplete ($icu_cpp/458 TUs)" >&2
  exit 1
}
(( runtime_cpp >= 128 )) || {
  echo "native-graph: ART runtime cache not promotable ($runtime_cpp TUs)" >&2
  exit 1
}
(( graphics_cpp >= 62 )) || {
  echo "native-graph: GraphicsJNI cache incomplete ($graphics_cpp TUs)" >&2
  exit 1
}
grep -q 'depfile = \$out.d' "$graph"
grep -q 'deps = gcc' "$graph"

# Phase edges must remain independently addressable. This is the build-time
# contract that keeps a graphics-input/framework edit from recompiling the
# HWUI implementation object or the ART bootstrap archive.
phase_rules=(
  runtime_filesystem_probe
  runtime_network_probe
  runtime_graphics_phase_probe
  runtime_graphics_input_probe
  runtime_graphics_state_probe
  runtime_graphics_session_probe
  runtime_jni_acceptance_probe
  runtime_hwui_probe
)
phase_sources=(
  runtime_filesystem_probe.cc
  runtime_network_probe.cc
  runtime_graphics_phase.cc
  runtime_graphics_input.cc
  runtime_graphics_state.cc
  runtime_graphics_session.cc
  runtime_jni_acceptance_probe.cc
  runtime_hwui_probe.cc
)
for index in "${!phase_rules[@]}"; do
  grep -q "^rule ${phase_rules[$index]}$" "$graph" || {
    echo "native-graph: missing phase rule ${phase_rules[$index]}" >&2
    exit 1
  }
  grep -q "probes/${phase_sources[$index]}" "$graph" || {
    echo "native-graph: missing narrow source edge ${phase_sources[$index]}" >&2
    exit 1
  }
done

phase_objects=(
  "$root/_build/runtime-probes/darwin_art_runtime_filesystem_probe.cc.o"
  "$root/_build/runtime-probes/darwin_art_runtime_network_probe.cc.o"
  "$root/_build/runtime-probes/darwin_art_runtime_graphics_phase.cc.o"
  "$root/_build/runtime-probes/darwin_art_runtime_graphics_input.cc.o"
  "$root/_build/runtime-probes/darwin_art_runtime_graphics_state.cc.o"
  "$root/_build/runtime-probes/darwin_art_runtime_graphics_session.cc.o"
  "$root/_build/runtime-probes/darwin_art_runtime_jni_acceptance_probe.cc.o"
  "$root/_build/runtime-probes/darwin_art_runtime_hwui_probe.cc.o"
)
# A graph generated by an older Ninja invocation may have stale entries in
# `.ninja_deps` even when the compiler fingerprint is current. Let Ninja
# reconcile those entries once; the following dry-run is the actual warm
# no-op assertion.
"$ninja" -f "$graph" "${phase_objects[@]}" >/dev/null
for object in "${phase_objects[@]}"; do
  phase_output="$($ninja -f "$graph" -n "$object" 2>&1)"
  grep -q 'no work to do' <<<"$phase_output" || {
    echo "native-graph: warm phase is not a no-op: $object" >&2
    echo "$phase_output" >&2
    exit 1
  }
  # The phase object may feed the final dylib, but it must not inherit a
  # bootstrap archive as a direct input.  Otherwise a framework/probe edit
  # silently widens the invalidation boundary back to the monolithic archive.
  phase_query="$($ninja -f "$graph" -t query "$object" 2>&1)"
  if grep -Eq 'runtime-bootstrap|runtime-graphics-bootstrap|hwui-static-foundation' <<<"$phase_query"; then
    echo "native-graph: phase edge widened by bootstrap input: $object" >&2
    echo "$phase_query" >&2
    exit 1
  fi
done

warm_output="$($ninja -f "$graph" -n icu-foundation 2>&1)"
grep -q 'no work to do' <<<"$warm_output" || {
  echo "native-graph: ICU warm target is not a no-op" >&2
  echo "$warm_output" >&2
  exit 1
}

echo "native-graph: PASS runtime=$runtime_cpp graphics-jni=$graphics_cpp icu=$icu_cpp cached-tu=$cached_cpp archives=$cached_archives phases=${#phase_rules[@]} warm=no-op depfiles=gcc"
