#!/usr/bin/env python3
"""Audit the pinned AOSP ARM64 optimizing-intrinsic inventory.

This derives the contract from pinned AOSP source. It does not maintain a
Darwin allowlist or mistake an upstream ordinary-call fallback for a missing
Darwin implementation.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys


def macro_entries(source: str, macro: str) -> list[str]:
    marker = f"#define {macro}(V)"
    start = source.find(marker)
    if start == -1:
        raise ValueError(f"missing macro {macro}")
    end = source.find("\n\n", start)
    if end == -1:
        raise ValueError(f"unterminated macro {macro}")
    return re.findall(r"\bV\(([A-Za-z0-9_]+),", source[start:end])


def unary_macro_entries(source: str, macro: str) -> set[str]:
    marker = f"#define {macro}(V)"
    start = source.find(marker)
    if start == -1:
        raise ValueError(f"missing macro {macro}")
    end = source.find("\n\n", start)
    if end == -1:
        raise ValueError(f"unterminated macro {macro}")
    return set(re.findall(r"\bV\(([A-Za-z0-9_]+)\)", source[start:end]))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--root",
        type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().parent.parent,
    )
    args = parser.parse_args()
    root = args.root.resolve()
    art = root / "_aosp" / "art"

    intrinsic_list = (art / "runtime" / "intrinsics_list.h").read_text()
    arm64_header = (
        art / "compiler" / "optimizing" / "code_generator_arm64.h"
    ).read_text()
    arm64_codegen = (
        art / "compiler" / "optimizing" / "intrinsics_arm64.cc"
    ).read_text()
    common_header = (art / "compiler" / "optimizing" / "intrinsics.h").read_text()

    signature = macro_entries(
        intrinsic_list, "ART_SIGNATURE_POLYMORPHIC_INTRINSICS_LIST"
    )
    specialized = macro_entries(
        intrinsic_list, "ART_INTRINSICS_WITH_SPECIALIZED_HIR_LIST"
    )
    hinvoke = macro_entries(intrinsic_list, "ART_INTRINSICS_WITH_HINVOKE_LIST")
    # The HInvoke macro ends by expanding the signature-polymorphic macro.
    hinvoke.extend(signature)

    errors: list[str] = []
    for label, values in (
        ("signature-polymorphic", signature),
        ("specialized-HIR", specialized),
        ("HInvoke", hinvoke),
    ):
        duplicates = sorted({value for value in values if values.count(value) > 1})
        if duplicates:
            errors.append(f"duplicate {label} entries: {', '.join(duplicates)}")

    locations = set(
        re.findall(
            r"IntrinsicLocationsBuilderARM64::Visit([A-Za-z0-9_]+)\s*\(",
            arm64_codegen,
        )
    )
    code = set(
        re.findall(
            r"IntrinsicCodeGeneratorARM64::Visit([A-Za-z0-9_]+)\s*\(",
            arm64_codegen,
        )
    )

    # These four visitor pairs are generated by BOXED_TYPES(VISIT_INTRINSIC).
    boxed = {f"{name}ValueOf" for name in ("Byte", "Short", "Character", "Integer")}
    if "BOXED_TYPES(VISIT_INTRINSIC)" not in arm64_codegen:
        errors.append("ARM64 boxed ValueOf visitor expansion disappeared")
    locations.update(boxed)
    code.update(boxed)

    unimplemented = unary_macro_entries(
        arm64_header, "UNIMPLEMENTED_INTRINSIC_LIST_ARM64"
    )
    unreachable = set(
        re.findall(
            r"UNREACHABLE_INTRINSIC\(Arch,\s*([A-Za-z0-9_]+)\)", common_header
        )
    )
    contract = set(hinvoke)
    implemented = contract & locations & code

    missing_location = contract - locations - unimplemented - unreachable
    missing_code = contract - code - unimplemented - unreachable
    partial = contract & (locations ^ code)
    classified = implemented | (contract & unimplemented) | (contract & unreachable)
    overlaps = (implemented & unimplemented) | (implemented & unreachable)

    if missing_location:
        errors.append("missing ARM64 locations: " + ", ".join(sorted(missing_location)))
    if missing_code:
        errors.append("missing ARM64 codegen: " + ", ".join(sorted(missing_code)))
    if partial:
        errors.append("unpaired ARM64 visitors: " + ", ".join(sorted(partial)))
    if classified != contract:
        errors.append(
            "unclassified HInvoke intrinsics: "
            + ", ".join(sorted(contract - classified))
        )
    if overlaps:
        errors.append("overlapping classifications: " + ", ".join(sorted(overlaps)))
    if unimplemented - contract:
        errors.append(
            "ARM64 unimplemented list has non-HInvoke entries: "
            + ", ".join(sorted(unimplemented - contract))
        )

    print(
        "ART ARM64 intrinsic inventory: "
        f"specialized-hir={len(specialized)} "
        f"hinvoke={len(contract)} "
        f"handwritten={len(implemented)} "
        f"upstream-call-fallback={len(contract & unimplemented)} "
        f"upstream-hir-rewrite={len(contract & unreachable)}"
    )
    if errors:
        for message in errors:
            print(f"error: {message}", file=sys.stderr)
        return 1
    print("ART ARM64 intrinsic source contract: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
