#!/bin/bash
set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
project_root="$(cd "$script_dir/.." && pwd)"
build_dir="$project_root/_build/graphics-foundations"
object_dir="$build_dir/objects"
libcutils="$project_root/_aosp/system/core/libcutils"
liblog="$project_root/_aosp/system/logging/liblog"
libutils="$project_root/_aosp/system/core/libutils"

# Android 16.0.0_r1 project revisions and module manifests. Archive streams
# generated by Gitiles are not byte-stable, so the extracted Android.bp files
# are the pinned source-manifest gate.
system_core_revision="68be0c2c0006a0740d0b1809abe4717308f90d15"
system_logging_revision="d78b713380007d3c0dde14712cbcbec27f491ad9"
libcutils_android_bp_sha="f67f553961de89e224c9d6435988d6757dac0a16701912dea15f8af61b603e88"
liblog_android_bp_sha="cb95bc9f49bd420d1448906541d31ce9f66996668aeee5d14693f64915af8199"
libutils_android_bp_sha="4a5103755fc434b3d3f02585c3646762373df9f659d751e39b91fa92d6cb2652"
libutils_binder_android_bp_sha="289e689e5d91bc6d595e23dfb70fbced35ccc80ef4835c8b51bd89f37457a066"

verify_sha256() {
  local path="$1"
  local expected="$2"
  if [[ ! -f "$path" ]]; then
    echo "graphics-foundations: missing pinned source $path" >&2
    return 1
  fi
  local actual
  actual="$(shasum -a 256 "$path" | awk '{print $1}')"
  if [[ "$actual" != "$expected" ]]; then
    echo "graphics-foundations: source manifest checksum mismatch: $path" >&2
    echo "expected=$expected actual=$actual" >&2
    return 1
  fi
}

verify_sha256 "$libcutils/Android.bp" "$libcutils_android_bp_sha"
verify_sha256 "$liblog/Android.bp" "$liblog_android_bp_sha"
verify_sha256 "$libutils/Android.bp" "$libutils_android_bp_sha"
verify_sha256 "$libutils/binder/Android.bp" "$libutils_binder_android_bp_sha"

# `libcutils` Android.bp: module base + target.host + target.not_windows,
# followed by the whole-static `libcutils_sockets` base + not_windows source.
libcutils_sources=(
  config_utils.cpp
  iosched_policy.cpp
  load_file.cpp
  native_handle.cpp
  properties.cpp
  record_stream.cpp
  strlcpy.c
  trace-host.cpp
  ashmem-host.cpp
  fs.cpp
  hashmap.cpp
  multiuser.cpp
  str_parms.cpp
  sockets.cpp
  socket_inaddr_any_server_unix.cpp
  socket_local_client_unix.cpp
  socket_local_server_unix.cpp
  socket_network_client_unix.cpp
  sockets_unix.cpp
)

# `liblog.defaults` Android.bp: liblog_sources + target.not_windows.
liblog_sources=(
  log_event_list.cpp
  log_event_write.cpp
  logger_name.cpp
  logger_read.cpp
  logger_write.cpp
  logprint.cpp
  properties.cpp
  event_tag_map.cpp
)

# `libutils_binder_impl_defaults_nodeps` is the whole-static support archive
# consumed by `libutils_impl_defaults`.
libutils_binder_sources=(
  Errors.cpp
  RefBase.cpp
  SharedBuffer.cpp
  String16.cpp
  String8.cpp
  StrongPointer.cpp
  Unicode.cpp
  VectorImpl.cpp
)

# `libutils_impl_defaults` base sources. Its target.linux Looper.cpp selection
# does not apply to the Darwin host variant.
libutils_core_sources=(
  FileMap.cpp
  JenkinsHash.cpp
  LightRefBase.cpp
  NativeHandle.cpp
  Printer.cpp
  StopWatch.cpp
  SystemClock.cpp
  Threads.cpp
  Timers.cpp
  Tokenizer.cpp
  misc.cpp
)

required_include_dirs=(
  "$libcutils/include"
  "$liblog/include"
  "$project_root/_aosp/system/libbase/include"
  "$project_root/_aosp/system/core/libutils/include"
  "$project_root/_aosp/system/core/libutils/binder/include"
  "$project_root/_aosp/system/core/libsystem/include"
)
for include_dir in "${required_include_dirs[@]}"; do
  if [[ ! -d "$include_dir" ]]; then
    echo "graphics-foundations: missing include subtree $include_dir" >&2
    echo "system/core revision=$system_core_revision" >&2
    echo "system/logging revision=$system_logging_revision" >&2
    exit 2
  fi
done

for source in "${libcutils_sources[@]}"; do
  if [[ ! -f "$libcutils/$source" ]]; then
    echo "graphics-foundations: missing system/core/libcutils/$source" >&2
    echo "required project=platform/system/core revision=$system_core_revision subtree=libcutils" >&2
    exit 2
  fi
done
for source in "${liblog_sources[@]}"; do
  if [[ ! -f "$liblog/$source" ]]; then
    echo "graphics-foundations: missing system/logging/liblog/$source" >&2
    echo "required project=platform/system/logging revision=$system_logging_revision subtree=liblog" >&2
    exit 2
  fi
done
for source in "${libutils_binder_sources[@]}"; do
  if [[ ! -f "$libutils/binder/$source" ]]; then
    echo "graphics-foundations: missing system/core/libutils/binder/$source" >&2
    echo "required project=platform/system/core revision=$system_core_revision subtree=libutils/binder" >&2
    exit 2
  fi
done
for source in "${libutils_core_sources[@]}"; do
  if [[ ! -f "$libutils/$source" ]]; then
    echo "graphics-foundations: missing system/core/libutils/$source" >&2
    echo "required project=platform/system/core revision=$system_core_revision subtree=libutils" >&2
    exit 2
  fi
done

cxx="$(command -v clang++)"
cc="$(command -v clang)"
if command -v llvm-ar >/dev/null 2>&1; then
  ar="$(command -v llvm-ar)"
else
  ar="$(xcrun --find ar)"
fi

common_flags=(
  -arch arm64
  -O2
  -fPIC
  -fvisibility=hidden
  -Wall
  -Werror
  -Wno-c99-designator
  -Wno-deprecated-declarations
  -I"$libcutils/include"
  -I"$liblog/include"
  -I"$project_root/_aosp/system/libbase/include"
  -I"$libutils/binder/include"
  -I"$libutils/include"
  -I"$project_root/_aosp/system/core/libsystem/include"
)

mkdir -p "$object_dir/liblog" "$object_dir/libcutils" \
  "$object_dir/libutils-binder" "$object_dir/libutils-core"

liblog_objects=()
for source in "${liblog_sources[@]}"; do
  object="$object_dir/liblog/${source%.*}.o"
  echo "graphics-foundations: compile liblog/$source"
  "$cxx" -std=gnu++20 "${common_flags[@]}" \
    -Wextra \
    -Wexit-time-destructors \
    -DLIBLOG_LOG_TAG=1006 \
    -DSNET_EVENT_LOG_TAG=1397638484 \
    -DANDROID_DEBUGGABLE=0 \
    -c "$liblog/$source" -o "$object"
  liblog_objects+=("$object")
done

libcutils_objects=()
for source in "${libcutils_sources[@]}"; do
  object="$object_dir/libcutils/${source%.*}.o"
  echo "graphics-foundations: compile libcutils/$source"
  compiler="$cxx"
  language_flags=(-std=gnu++20)
  if [[ "$source" == *.c ]]; then
    compiler="$cc"
    language_flags=(-std=gnu17)
  fi
  "$compiler" "${language_flags[@]}" "${common_flags[@]}" \
    -Wextra \
    -Wno-exit-time-destructors \
    -c "$libcutils/$source" -o "$object"
  libcutils_objects+=("$object")
done

libutils_binder_objects=()
for source in "${libutils_binder_sources[@]}"; do
  object="$object_dir/libutils-binder/${source%.cpp}.o"
  echo "graphics-foundations: compile libutils/binder/$source"
  "$cxx" -std=gnu++20 "${common_flags[@]}" \
    -Wno-exit-time-destructors \
    -Wno-unused-parameter \
    -Winvalid-offsetof \
    -Wsequence-point \
    -Wzero-as-null-pointer-constant \
    -DANDROID_UTILS_REF_BASE_DISABLE_IMPLICIT_CONSTRUCTION \
    -c "$libutils/binder/$source" -o "$object"
  libutils_binder_objects+=("$object")
done

libutils_core_objects=()
for source in "${libutils_core_sources[@]}"; do
  object="$object_dir/libutils-core/${source%.cpp}.o"
  echo "graphics-foundations: compile libutils/$source"
  "$cxx" -std=gnu++20 "${common_flags[@]}" \
    -Wno-exit-time-destructors \
    -Wno-unused-parameter \
    -DANDROID_UTILS_REF_BASE_DISABLE_IMPLICIT_CONSTRUCTION \
    -c "$libutils/$source" -o "$object"
  libutils_core_objects+=("$object")
done

liblog_archive="$build_dir/liblog-darwin.a"
libcutils_archive="$build_dir/libcutils-darwin.a"
libutils_binder_archive="$build_dir/libutils-binder-darwin.a"
libutils_archive="$build_dir/libutils-darwin.a"
"$ar" rcs "$liblog_archive" "${liblog_objects[@]}"
"$ar" rcs "$libcutils_archive" "${libcutils_objects[@]}"
"$ar" rcs "$libutils_binder_archive" "${libutils_binder_objects[@]}"
# Android.bp whole_static_libs means the final libutils archive owns every
# binder support object rather than merely referring to a nested archive.
"$ar" rcs "$libutils_archive" \
  "${libutils_core_objects[@]}" "${libutils_binder_objects[@]}"

for object in "${liblog_objects[@]}" "${libcutils_objects[@]}" \
    "${libutils_binder_objects[@]}" "${libutils_core_objects[@]}"; do
  kind="$(file "$object")"
  if [[ "$kind" != *"Mach-O 64-bit object arm64"* ]]; then
    echo "graphics-foundations: unexpected object format: $kind" >&2
    exit 3
  fi
done
for archive in "$liblog_archive" "$libcutils_archive" \
    "$libutils_binder_archive" "$libutils_archive"; do
  architectures="$(lipo -archs "$archive")"
  if [[ "$architectures" != "arm64" ]]; then
    echo "graphics-foundations: unexpected archive architectures: $archive: $architectures" >&2
    exit 3
  fi
done

archive_members() {
  "$ar" -t "$1" | grep -v '^__\.SYMDEF'
}

verify_member_manifest() {
  local archive="$1"
  shift
  local expected actual
  expected="$(printf '%s\n' "$@" | sort)"
  actual="$(archive_members "$archive" | sort)"
  if [[ "$actual" != "$expected" ]]; then
    echo "graphics-foundations: archive member manifest mismatch: $archive" >&2
    diff <(printf '%s\n' "$expected") <(printf '%s\n' "$actual") >&2 || true
    exit 3
  fi
}

binder_members=()
for source in "${libutils_binder_sources[@]}"; do
  binder_members+=("${source%.cpp}.o")
done
core_members=()
for source in "${libutils_core_sources[@]}"; do
  core_members+=("${source%.cpp}.o")
done
verify_member_manifest "$libutils_binder_archive" "${binder_members[@]}"
verify_member_manifest "$libutils_archive" "${core_members[@]}" "${binder_members[@]}"

libutils_definitions="$(nm -gU "$libutils_archive")"
required_utils_patterns=(
  '__ZN7android7RefBaseC'
  '__ZN7android7String8C'
  '_utf8_to_utf16_length'
  '__ZN7android10VectorImplC'
)
for pattern in "${required_utils_patterns[@]}"; do
  if ! grep -F " T $pattern" <<<"$libutils_definitions" >/dev/null; then
    echo "graphics-foundations: libutils archive lacks representative definition $pattern" >&2
    exit 4
  fi
done

closure="$project_root/_build/hwui-canvas-gate/undefined-symbols.txt"
if [[ ! -f "$closure" ]]; then
  echo "graphics-foundations: HWUI Canvas undefined-symbol closure is missing: $closure" >&2
  echo "run tools/compile-android16-hwui-canvas-gate.sh first" >&2
  exit 4
fi
skia_archive="$project_root/_build/skia/libskia.a"
if [[ ! -f "$skia_archive" ]]; then
  echo "graphics-foundations: Android-framework Skia archive is missing" >&2
  echo "run cargo run -p art-bootstrap -- build-skia first" >&2
  exit 4
fi
required_log_symbols=(___android_log_assert ___android_log_print)
liblog_definitions="$(nm -gU "$liblog_archive")"
for symbol in "${required_log_symbols[@]}"; do
  if ! grep -Fxq "$symbol" "$closure"; then
    echo "graphics-foundations: expected HWUI closure symbol missing: $symbol" >&2
    exit 4
  fi
  if ! grep -F " $symbol" <<<"$liblog_definitions" >/dev/null; then
    echo "graphics-foundations: liblog archive does not define $symbol" >&2
    exit 4
  fi
done

closure_count="$(wc -l < "$closure" | tr -d ' ')"
skia_resolved_count="$({
  nm -gU "$skia_archive" | awk '$2 ~ /^[TDSB]$/ { print $3 }' | sort -u
} | comm -12 <(sort "$closure") - | wc -l | tr -d ' ')"
remaining_direct_count=$((closure_count - skia_resolved_count - ${#required_log_symbols[@]}))
if [[ "$closure_count" != 278 || "$skia_resolved_count" != 149 ||
      "$remaining_direct_count" != 127 ]]; then
  echo "graphics-foundations: direct closure accounting changed" >&2
  echo "closure=$closure_count skia=$skia_resolved_count remaining=$remaining_direct_count" >&2
  exit 4
fi

echo "graphics-foundations: liblog_sources=${#liblog_sources[@]} libcutils_sources=${#libcutils_sources[@]}"
echo "graphics-foundations: libutils_core=${#libutils_core_sources[@]} libutils_binder=${#libutils_binder_sources[@]} final_members=$(archive_members "$libutils_archive" | wc -l | tr -d ' ')"
echo "graphics-foundations: arm64 archives=$liblog_archive,$libcutils_archive,$libutils_binder_archive,$libutils_archive"
echo "graphics-foundations: hwui-closure=$closure_count resolved-skia=$skia_resolved_count resolved-liblog=${#required_log_symbols[@]} remaining-direct=$remaining_direct_count"
