#!/bin/bash
set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
project_root="$(cd "$script_dir/.." && pwd)"
build_dir="$project_root/_build/graphics-foundations"
object_dir="$build_dir/objects"
libcutils="$project_root/_aosp/system/core/libcutils"
liblog="$project_root/_aosp/system/logging/liblog"

# Android 16.0.0_r1 project revisions and module manifests. Archive streams
# generated by Gitiles are not byte-stable, so the extracted Android.bp files
# are the pinned source-manifest gate.
system_core_revision="68be0c2c0006a0740d0b1809abe4717308f90d15"
system_logging_revision="d78b713380007d3c0dde14712cbcbec27f491ad9"
libcutils_android_bp_sha="f67f553961de89e224c9d6435988d6757dac0a16701912dea15f8af61b603e88"
liblog_android_bp_sha="cb95bc9f49bd420d1448906541d31ce9f66996668aeee5d14693f64915af8199"

verify_sha256() {
  local path="$1"
  local expected="$2"
  if [[ ! -f "$path" ]]; then
    echo "graphics-foundations: missing pinned source $path" >&2
    return 1
  fi
  local actual
  actual="$(shasum -a 256 "$path" | awk '{print $1}')"
  if [[ "$actual" != "$expected" ]]; then
    echo "graphics-foundations: source manifest checksum mismatch: $path" >&2
    echo "expected=$expected actual=$actual" >&2
    return 1
  fi
}

verify_sha256 "$libcutils/Android.bp" "$libcutils_android_bp_sha"
verify_sha256 "$liblog/Android.bp" "$liblog_android_bp_sha"

# `libcutils` Android.bp: module base + target.host + target.not_windows,
# followed by the whole-static `libcutils_sockets` base + not_windows source.
libcutils_sources=(
  config_utils.cpp
  iosched_policy.cpp
  load_file.cpp
  native_handle.cpp
  properties.cpp
  record_stream.cpp
  strlcpy.c
  trace-host.cpp
  ashmem-host.cpp
  fs.cpp
  hashmap.cpp
  multiuser.cpp
  str_parms.cpp
  sockets.cpp
  socket_inaddr_any_server_unix.cpp
  socket_local_client_unix.cpp
  socket_local_server_unix.cpp
  socket_network_client_unix.cpp
  sockets_unix.cpp
)

# `liblog.defaults` Android.bp: liblog_sources + target.not_windows.
liblog_sources=(
  log_event_list.cpp
  log_event_write.cpp
  logger_name.cpp
  logger_read.cpp
  logger_write.cpp
  logprint.cpp
  properties.cpp
  event_tag_map.cpp
)

required_include_dirs=(
  "$libcutils/include"
  "$liblog/include"
  "$project_root/_aosp/system/libbase/include"
  "$project_root/_aosp/system/core/libutils/include"
  "$project_root/_aosp/system/core/libsystem/include"
)
for include_dir in "${required_include_dirs[@]}"; do
  if [[ ! -d "$include_dir" ]]; then
    echo "graphics-foundations: missing include subtree $include_dir" >&2
    echo "system/core revision=$system_core_revision" >&2
    echo "system/logging revision=$system_logging_revision" >&2
    exit 2
  fi
done

for source in "${libcutils_sources[@]}"; do
  if [[ ! -f "$libcutils/$source" ]]; then
    echo "graphics-foundations: missing system/core/libcutils/$source" >&2
    echo "required project=platform/system/core revision=$system_core_revision subtree=libcutils" >&2
    exit 2
  fi
done
for source in "${liblog_sources[@]}"; do
  if [[ ! -f "$liblog/$source" ]]; then
    echo "graphics-foundations: missing system/logging/liblog/$source" >&2
    echo "required project=platform/system/logging revision=$system_logging_revision subtree=liblog" >&2
    exit 2
  fi
done

cxx="$(command -v clang++)"
cc="$(command -v clang)"
if command -v llvm-ar >/dev/null 2>&1; then
  ar="$(command -v llvm-ar)"
else
  ar="$(xcrun --find ar)"
fi

common_flags=(
  -arch arm64
  -O2
  -fPIC
  -fvisibility=hidden
  -Wall
  -Wextra
  -Werror
  -Wno-c99-designator
  -Wno-deprecated-declarations
  -I"$libcutils/include"
  -I"$liblog/include"
  -I"$project_root/_aosp/system/libbase/include"
  -I"$project_root/_aosp/system/core/libutils/include"
  -I"$project_root/_aosp/system/core/libsystem/include"
)

mkdir -p "$object_dir/liblog" "$object_dir/libcutils"

liblog_objects=()
for source in "${liblog_sources[@]}"; do
  object="$object_dir/liblog/${source%.*}.o"
  echo "graphics-foundations: compile liblog/$source"
  "$cxx" -std=gnu++20 "${common_flags[@]}" \
    -Wexit-time-destructors \
    -DLIBLOG_LOG_TAG=1006 \
    -DSNET_EVENT_LOG_TAG=1397638484 \
    -DANDROID_DEBUGGABLE=0 \
    -c "$liblog/$source" -o "$object"
  liblog_objects+=("$object")
done

libcutils_objects=()
for source in "${libcutils_sources[@]}"; do
  object="$object_dir/libcutils/${source%.*}.o"
  echo "graphics-foundations: compile libcutils/$source"
  compiler="$cxx"
  language_flags=(-std=gnu++20)
  if [[ "$source" == *.c ]]; then
    compiler="$cc"
    language_flags=(-std=gnu17)
  fi
  "$compiler" "${language_flags[@]}" "${common_flags[@]}" \
    -Wno-exit-time-destructors \
    -c "$libcutils/$source" -o "$object"
  libcutils_objects+=("$object")
done

liblog_archive="$build_dir/liblog-darwin.a"
libcutils_archive="$build_dir/libcutils-darwin.a"
"$ar" rcs "$liblog_archive" "${liblog_objects[@]}"
"$ar" rcs "$libcutils_archive" "${libcutils_objects[@]}"

for object in "${liblog_objects[@]}" "${libcutils_objects[@]}"; do
  kind="$(file "$object")"
  if [[ "$kind" != *"Mach-O 64-bit object arm64"* ]]; then
    echo "graphics-foundations: unexpected object format: $kind" >&2
    exit 3
  fi
done
for archive in "$liblog_archive" "$libcutils_archive"; do
  architectures="$(lipo -archs "$archive")"
  if [[ "$architectures" != "arm64" ]]; then
    echo "graphics-foundations: unexpected archive architectures: $archive: $architectures" >&2
    exit 3
  fi
done

closure="$project_root/_build/hwui-canvas-gate/undefined-symbols.txt"
if [[ ! -f "$closure" ]]; then
  echo "graphics-foundations: HWUI Canvas undefined-symbol closure is missing: $closure" >&2
  echo "run tools/compile-android16-hwui-canvas-gate.sh first" >&2
  exit 4
fi
skia_archive="$project_root/_build/skia/libskia.a"
if [[ ! -f "$skia_archive" ]]; then
  echo "graphics-foundations: Android-framework Skia archive is missing" >&2
  echo "run cargo run -p art-bootstrap -- build-skia first" >&2
  exit 4
fi
required_log_symbols=(___android_log_assert ___android_log_print)
liblog_definitions="$(nm -gU "$liblog_archive")"
for symbol in "${required_log_symbols[@]}"; do
  if ! grep -Fxq "$symbol" "$closure"; then
    echo "graphics-foundations: expected HWUI closure symbol missing: $symbol" >&2
    exit 4
  fi
  if ! grep -F " $symbol" <<<"$liblog_definitions" >/dev/null; then
    echo "graphics-foundations: liblog archive does not define $symbol" >&2
    exit 4
  fi
done

closure_count="$(wc -l < "$closure" | tr -d ' ')"
skia_resolved_count="$({
  nm -gU "$skia_archive" | awk '$2 ~ /^[TDSB]$/ { print $3 }' | sort -u
} | comm -12 <(sort "$closure") - | wc -l | tr -d ' ')"
remaining_direct_count=$((closure_count - skia_resolved_count - ${#required_log_symbols[@]}))
if [[ "$closure_count" != 278 || "$skia_resolved_count" != 149 ||
      "$remaining_direct_count" != 127 ]]; then
  echo "graphics-foundations: direct closure accounting changed" >&2
  echo "closure=$closure_count skia=$skia_resolved_count remaining=$remaining_direct_count" >&2
  exit 4
fi

echo "graphics-foundations: liblog_sources=${#liblog_sources[@]} libcutils_sources=${#libcutils_sources[@]}"
echo "graphics-foundations: arm64 archives=$liblog_archive,$libcutils_archive"
echo "graphics-foundations: hwui-closure=$closure_count resolved-skia=$skia_resolved_count resolved-liblog=${#required_log_symbols[@]} remaining-direct=$remaining_direct_count"
