#![forbid(unsafe_code)]

use sha2::{Digest, Sha256};
use std::env;
use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};

const GRAPH_VERSION: &str = "darwin-art-native-graph-v1";

fn main() {
    if let Err(error) = run() {
        eprintln!("darwin-art-xtask: {error}");
        std::process::exit(2);
    }
}

fn run() -> Result<(), String> {
    let mut args = env::args().skip(1);
    match args.next().as_deref() {
        Some("native-graph") => {
            let mut out = None;
            while let Some(arg) = args.next() {
                match arg.as_str() {
                    "--out" => out = args.next().map(PathBuf::from),
                    value => return Err(format!("unknown native-graph option: {value}")),
                }
            }
            let out = out.ok_or_else(|| "native-graph requires --out <path>".to_owned())?;
            emit_graph(&out).map_err(|error| error.to_string())
        }
        _ => Err("usage: cargo run -p darwin-art-xtask -- native-graph --out <path>".to_owned()),
    }
}

fn emit_graph(out: &Path) -> io::Result<()> {
    let root = repository_root(out);
    let inputs = graph_inputs(&root);
    let digest = digest_inputs(&root, &inputs)?;
    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent)?;
    }
    let digest_path = out.with_extension("inputs.sha256");
    fs::write(&digest_path, format!("{digest}  {GRAPH_VERSION}\n"))?;

    let root_for_shell = root.to_string_lossy().into_owned();
    let stamp = ninja_path(&out.with_extension("graphics-bootstrap.stamp"));
    let stamp_for_shell = out
        .with_extension("graphics-bootstrap.stamp")
        .canonicalize()
        .unwrap_or_else(|_| out.with_extension("graphics-bootstrap.stamp").to_path_buf());
    let input_list = inputs
        .iter()
        .map(|path| ninja_path(&root.join(path)))
        .collect::<Vec<_>>()
        .join(" ");

    let mut graph = String::new();
    graph.push_str("# Generated by darwin-art-xtask. Do not edit.\n");
    graph.push_str("ninja_required_version = 1.10\n\n");
    graph.push_str("rule graphics_bootstrap\n");
    graph.push_str("  command = cd ");
    graph.push_str(&shell_quote(&root_for_shell));
    graph.push_str(" && cargo run -p art-bootstrap -- build-runtime-graphics-bootstrap && touch ");
    graph.push_str(&shell_quote(&stamp_for_shell.to_string_lossy()));
    graph.push('\n');
    graph.push_str("  description = GRAPHICS bootstrap\n");
    graph.push_str("  restat = 1\n\n");
    graph.push_str("build ");
    graph.push_str(&stamp);
    graph.push_str(": graphics_bootstrap ");
    graph.push_str(&input_list);
    graph.push('\n');
    graph.push_str("build graphics-bootstrap: phony ");
    graph.push_str(&stamp);
    graph.push('\n');
    graph.push_str("build graph-input-digest: phony ");
    graph.push_str(&ninja_path(&digest_path));
    graph.push('\n');

    let mut file = fs::File::create(out)?;
    file.write_all(graph.as_bytes())?;
    println!(
        "darwin-art-xtask: wrote {} (inputs={} digest={digest})",
        out.display(),
        inputs.len()
    );
    Ok(())
}

fn repository_root(out: &Path) -> PathBuf {
    let start = if out.is_absolute() {
        out.parent().unwrap_or(out).to_path_buf()
    } else {
        env::current_dir().unwrap_or_else(|_| PathBuf::from("."))
    };
    start
        .ancestors()
        .find(|candidate| candidate.join("Cargo.toml").is_file())
        .unwrap_or(start.as_path())
        .to_path_buf()
}

fn graph_inputs(root: &Path) -> Vec<PathBuf> {
    let mut paths = vec![
        PathBuf::from("Cargo.toml"),
        PathBuf::from("Cargo.lock"),
        PathBuf::from("crates/art-bootstrap/Cargo.toml"),
        PathBuf::from("crates/art-bootstrap/src/main.rs"),
        PathBuf::from("probes/runtime_link_probe.cc"),
        PathBuf::from("compat/darwin_runtime_adapters.cc"),
        PathBuf::from("tools/build-android16-skia-hwui-force-load.sh"),
        PathBuf::from("tools/build-android16-hwui-static-foundation.sh"),
    ];
    for directory in ["compat", "probes", "crates/art-bootstrap/src"] {
        collect_files(&root.join(directory), root, &mut paths);
    }
    paths.sort();
    paths.dedup();
    paths.retain(|path| root.join(path).is_file());
    paths
}

fn collect_files(directory: &Path, root: &Path, output: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(directory) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_files(&path, root, output);
        } else if path.is_file() {
            if let Ok(relative) = path.strip_prefix(root) {
                output.push(relative.to_path_buf());
            }
        }
    }
}

fn digest_inputs(root: &Path, inputs: &[PathBuf]) -> io::Result<String> {
    let mut digest = Sha256::new();
    digest.update(GRAPH_VERSION.as_bytes());
    for path in inputs {
        digest.update(path.to_string_lossy().as_bytes());
        digest.update([0]);
        digest.update(fs::read(root.join(path))?);
        digest.update([0]);
    }
    Ok(format!("{:x}", digest.finalize()))
}

fn ninja_path(path: &Path) -> String {
    path.to_string_lossy().replace('$', "$$").replace(' ', "$ ")
}

fn shell_quote(path: &str) -> String {
    if path
        .bytes()
        .all(|byte| byte.is_ascii_alphanumeric() || b"_./-".contains(&byte))
    {
        path.to_owned()
    } else {
        format!("'{}'", path.replace('\'', "'\\''"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn shell_quote_is_stable_for_normal_repository_paths() {
        assert_eq!(shell_quote("/tmp/darwin-art"), "/tmp/darwin-art");
        assert_eq!(shell_quote("/tmp/with space"), "'/tmp/with space'");
    }

    #[test]
    fn ninja_path_escapes_ninja_metacharacters() {
        assert_eq!(ninja_path(Path::new("a b/$c")), "a$ b/$$c");
    }
}
