#!/usr/bin/env python3
"""Emit the locked JNI slot constants from an Android NDK jni.h."""

import hashlib
import pathlib
import re
import sys


def declarations(source: str, structure: str) -> list[str]:
    match = re.search(rf"struct {structure}\s*\{{(.*?)\n\}};", source, re.S)
    if match is None:
        raise ValueError(f"missing {structure}")
    body = re.sub(r"/\*.*?\*/", "", match.group(1), flags=re.S)
    return [item.strip() for item in body.split(";") if item.strip()]


def slot_names(source: str, structure: str) -> list[str]:
    result = []
    for declaration in declarations(source, structure):
        function = re.search(r"\(\*\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)", declaration)
        if function is not None:
            result.append(function.group(1))
            continue
        reserved = re.search(r"\b(reserved[0-9]+)\s*$", declaration)
        if reserved is None:
            raise ValueError(f"unparsed declaration in {structure}: {declaration!r}")
        result.append(reserved.group(1))
    return result


def digest(names: list[str]) -> str:
    return hashlib.sha256(("\n".join(names) + "\n").encode()).hexdigest()


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: generate_slots.py <jni.h>", file=sys.stderr)
        return 2
    source = pathlib.Path(sys.argv[1]).read_text(encoding="utf-8")
    native = slot_names(source, "JNINativeInterface")
    invoke = slot_names(source, "JNIInvokeInterface")
    required_native = [
        "GetVersion",
        "FindClass",
        "ThrowNew",
        "ExceptionOccurred",
        "ExceptionClear",
        "NewGlobalRef",
        "DeleteGlobalRef",
        "DeleteLocalRef",
        "NewLocalRef",
        "NewStringUTF",
        "GetStringUTFLength",
        "GetStringUTFChars",
        "ReleaseStringUTFChars",
        "GetArrayLength",
        "NewByteArray",
        "GetByteArrayRegion",
        "SetByteArrayRegion",
        "RegisterNatives",
        "ExceptionCheck",
    ]
    required_invoke = ["GetEnv"]

    print("/* Generated by tools/generate_slots.py; do not edit. */")
    print("#ifndef DARWIN_ART_ANDROID_JNI_SLOTS_H_")
    print("#define DARWIN_ART_ANDROID_JNI_SLOTS_H_")
    print(f"#define DARWIN_ART_JNI_NATIVE_SLOT_COUNT {len(native)}u")
    print(f"#define DARWIN_ART_JNI_INVOKE_SLOT_COUNT {len(invoke)}u")
    for name in required_native:
        print(f"#define DARWIN_ART_JNI_SLOT_{name} {native.index(name)}u")
    for name in required_invoke:
        print(f"#define DARWIN_ART_JNI_INVOKE_SLOT_{name} {invoke.index(name)}u")
    print(f'#define DARWIN_ART_JNI_NATIVE_NAMES_SHA256 "{digest(native)}"')
    print(f'#define DARWIN_ART_JNI_INVOKE_NAMES_SHA256 "{digest(invoke)}"')
    print("#endif")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
