[package]
name = "darwin-art-host"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
darwin-art-abi = { path = "../darwin-art-abi" }
darwin-art-engine-sys = { path = "../darwin-art-engine-sys" }
darwin-art-engine = { path = "../darwin-art-engine" }
darwin-art-runtime = { path = "../darwin-art-runtime" }
darwin-art-profile = { path = "../darwin-art-profile" }
