use std::fs;
use std::io;
use std::path::Path;

/// Publish graph metadata as one complete file. A killed xtask must leave the
/// previous Ninja graph/cache stamp usable rather than a truncated file.
pub(crate) fn write(path: &Path, bytes: &[u8]) -> io::Result<()> {
    // Graph emission happens before every native invocation. Preserve the
    // previous inode and mtime when the generated bytes are identical so
    // Ninja never mistakes orchestration for an input change.
    if fs::read(path).is_ok_and(|current| current == bytes) {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let temporary = path.with_extension(format!("darwin-art-xtask-tmp-{}", std::process::id()));
    fs::write(&temporary, bytes)?;
    fs::rename(temporary, path)
}

#[cfg(test)]
mod tests {
    use super::write;
    use std::fs;
    use std::thread;
    use std::time::Duration;

    #[test]
    fn identical_write_preserves_timestamp() {
        let directory =
            std::env::temp_dir().join(format!("darwin-art-atomic-write-{}", std::process::id()));
        fs::create_dir_all(&directory).unwrap();
        let path = directory.join("graph.ninja");
        write(&path, b"same bytes\n").unwrap();
        let before = fs::metadata(&path).unwrap().modified().unwrap();
        thread::sleep(Duration::from_millis(20));
        write(&path, b"same bytes\n").unwrap();
        let after = fs::metadata(&path).unwrap().modified().unwrap();
        assert_eq!(before, after);
        fs::remove_file(path).unwrap();
        fs::remove_dir(directory).unwrap();
    }
}
