[package]
name = "bionic-fs-facade"
version = "0.1.0"
edition = "2024"
publish = false
build = "build.rs"

[dependencies]
darwin-art-elf-loader = { path = "../../crates/darwin-art-elf-loader" }
darwin-art-fs-broker = { path = "../../crates/darwin-art-fs-broker" }
darwin-art-prefix = { path = "../../crates/darwin-art-prefix" }
