[package]
name = "bionic-process-state-facade"
version = "0.1.0"
edition = "2024"
publish = false
build = "build.rs"

[features]
standalone-syscall = []

[[bin]]
name = "bionic-process-state-facade"
path = "src/main.rs"
required-features = ["standalone-syscall"]

[dependencies]
darwin-art-elf-loader = { path = "../../crates/darwin-art-elf-loader" }
