[package]
name = "bionic-runtime-provider-closure"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
bionic-fs-facade = { path = "../bionic-fs-facade" }
bionic-process-state-facade = { path = "../bionic-process-state-facade" }
bionic-stdio-facade = { path = "../bionic-stdio-facade" }
bionic-dso-lifecycle-facade = { path = "../bionic-dso-lifecycle-facade" }
bionic-vm-facade = { path = "../bionic-vm-facade" }
android-dso-namespace = { path = "../android-dso-namespace" }

[workspace]
