[workspace]
members = [
    "crates/art-bootstrap",
    "crates/darwin-art-host",
    "crates/darwin-art-prefix",
    "crates/darwin-art-elf-loader",
    "crates/darwin-art-fs-broker",
    "crates/darwin-art-abi",
    "crates/darwin-art-engine-sys",
    "crates/darwin-art-engine",
    "crates/darwin-art-runtime",
    "crates/darwin-art-xtask",
]
default-members = ["crates/art-bootstrap", "crates/darwin-art-host", "crates/darwin-art-prefix"]
resolver = "2"
